### ISSUE TITLE
请问“ThinkPad UEFI固件白名单去除”是在什么机器上测试成功的呢？

### ISSUE THREAD

**Issue by polarlights** [mytbk/firmware_notes#1]
非常高兴竟然看到了 TP 的 BIOS 白名单去除方法，您在文档中写的实在什么机器上测试的呢？是否用通用性？谢谢。 我有一个 TP T430。谢谢

**Comment by mytbk** [comment]
我写的时候是在一台X220上做的，最近51nb那里有人用了这个方法在W530上也通过了。
其实这个方法靠的还是运气，最准确的方法还是老实地逆向，但我一直没时间研究UEFI的结构。
http://forum.51nb.com/forum.php?mod=viewthread&tid=1623560&highlight=W530%2B%B0%D7%C3%FB%B5%A5

**Comment by polarlights** [comment]
此方案比原来单纯修改 ID 会通用性好很多。请问能否把它转到 bbs.pcbeta.com？让更多的人实验下。保留原文链接。谢谢

**Comment by mytbk** [comment]
可以。同时我也会根据大家的测试结果更新我的文章。

**Comment by polarlights** [comment]
OMT， Thinkpad 的 BIOS 芯片型号是什么的呢，因为需要买编程器和编程夹烧录 BIOS。谢谢。

**Comment by polarlights** [comment]
OMT， Thinkpad 的 BIOS 芯片型号是什么的呢，因为需要买编程器和编程夹烧录 BIOS。谢谢。

**Comment by polarlights** [comment]
OMT， Thinkpad 的 BIOS 芯片型号是什么的呢，因为需要买编程器和编程夹烧录 BIOS。谢谢。

**Comment by polarlights** [comment]
OMT， Thinkpad 的 BIOS 芯片型号是什么的呢，因为需要买编程器和编程夹烧录 BIOS。谢谢。

**Comment by mytbk** [comment]
笔记本的BIOS芯片一般都是25系列的，比如常见的MX**25**L6445E,MX**25**L3205E,W**25**QCV.
具体到一个笔记本上可以拆开机子用放大镜看，如果是单芯片BIOS的话可以用```flashrom -p internal:laptop=force_I_want_a_brick```探测。

还有，我这篇文章末尾提到的那篇**xx30 whitelist removal**那篇文章提到了一个机器的拆机图和芯片型号。

**Comment by polarlights** [comment]
我发现我的 BIOS 里面没有 EndPoint，直接 Copy 你的转换代码可以吗？谢谢

**Comment by mytbk** [comment]
你说的是EntryPoint吗？EFI程序都是PE文件，而且都有入口点，没有EntryPoint肯定就错了。你要找LenovoWmaPolicyDxe.efi,而且要提取的是PE32
Image Section.

**Comment by polarlights** [comment]
是的。现在我使用编程夹不拆芯片直接读取，看有人说需要在芯片的第八个引脚上加3.3V 电压，但是不知道主板的 GND 是哪个。直接加在编程器的第八个引脚上貌似是不可以的。

**Comment by polarlights** [comment]
刚才从联想官网下了一个 BIOS，解开，里面也没有 EndPoint，只有 Type:0x10, Size: 0x001EC0

**Comment by mytbk** [comment]
我下了个X250的BIOS,用刚刚编译的最新git代码的UEFITool打开N10ET38W/$01E5000.FL1,定位到LenovoWmaPolicyDxe.efi下PE32 Image Section,看到的是这些:

Type: 10h
Full size: 1164h (4452)
Header size: 4h (4)
Body size: 1160h (4448)
DOS signature: 5A4Dh
PE signature: 00004550h
Machine type: x86-64
Number of sections: 4
Characteristics: 2022h
Optional header signature: 020Bh
Subsystem: 000Bh
RelativeEntryPoint: CBCh
BaseOfCode: 280h
ImageBase: 0h
EntryPoint: CBCh

**Comment by polarlights** [comment]
好吧。看来我的 UEFI 的版本太低了，用 GITHUB 上最新的居然 OK 了。么么……谢谢。下周有空再搞咯。哎……

**Comment by polarlights** [comment]
最近搞了个 T450s，刷了最新版本的 BIOS。我在想如果直接用 BIOS 升级程序里面的 FL1文件，去除EC 头前面的数据，直接改是否靠谱？谢谢

**Comment by mytbk** [comment]
厂商的工具可能会对文件进行验证，并阻止刷入被修改过的文件。
此外我不清楚broadwell(及之后)的平台中引入的Intel boot guard的情况，不过我见过有人改了BIOS也能正常使用的。
