### ISSUE TITLE
请问能帮忙去除一个MSR 0xE2锁么？

### ISSUE THREAD

**Issue by tofuliang** [mytbk/firmware_notes#8]
主板是 Alienware Aurora R4，BIOS版本是 A07(最新版是A11，一直没升级)，在装黑苹果的时候因为变频问题需要解锁 MSR 0xE2,

参照[MSR解锁教程](https://github.com/acidanthera/AppleSupportPkg#verifymsre2)去弄的时候,发现setup.txt里并没有相关的设置项。

参照[菜单取消隐藏](https://forums.mydigitallife.net/threads/tutorial-ami-aptio-uefi-advanced-menu-unlock-bonus-msr-unlock.54523/)把BIOS的隐藏菜单全打开了，刷入到主板，仍旧没有相关选项。

在UEFITool中直接搜索`CFG`,有一个结果，且定位在`CORE_DEX`的PE32 image中，但是解压出来后，用16进制编辑工具再次搜索又没有结果。

<img width="800" alt="CFG_in_PE32" src="https://user-images.githubusercontent.com/1814685/71642639-526b7e80-2ce9-11ea-908a-2df621a4858e.png">

在`A07`和`A11`中都是这样，但是涉及到EFI反编译这块，自问真没有这个能力。。。所以能否帮看看？

附件中的A07.rom是我修改过，已经取消隐藏菜单的，A11.rom是从官方BIOS升级程序中提出来的。
[BIOS.zip](https://github.com/mytbk/firmware_notes/files/4014169/BIOS.zip)

**Comment by mytbk** [comment]
看了下你给的固件，ME版本是8.1.40.1416，看起来是Haswell标压的平台？
我刚才找了一份Haswell的源码看了下，找到了关于MSR 0xE2的相关代码，但是在你给的UEFI镜像里面找不到相同GUID的模块，要定位这段代码有点难度了。有时间我再看一下。

**Comment by tofuliang** [comment]
是 [X79](https://ark.intel.com/content/www/us/en/ark/products/64015/intel-x79-express-chipset.html) 的平台，支持Sandy Bridge-E 和 Ivy Bridge-E 的CPU，按照MSR 0xE2解锁的教程，一般BIOS都是有解锁菜单选项的，只是隐藏了而已，通过“CFG Lock”关键词就能找出来。但是我这个感觉是直接hardcode了，隐藏菜单也没有相关选项，查找“CFG”关键词也只能在CORE_DEX里有一个唯一匹配(不过也不确定就是这里。)

PS.
[这里](https://www.bios-mods.com/forum/Thread-Aurora-R4-NVMe-bios-support) 有一个加入了Nvme支持的,不知道对于逆向有没有帮助。
```
Updated BIOS file containing the following fix

Based on A11
- Native NVMe booting via PCIe adaptor
- Microcode fix for Spectre bug
- Updated NIC firmware
- Updated RST firmware to support RAID TRIM

Please refer to the link of the BIOS file as well as AFUDOS (need to run natively on USB-BOOT DOS and not DOS Box)
http://s000.tinyupload.com/index.php?file_id=02614479157579325788

Aside from that, here's the update to fix Intel ME bug
Please refer to the link of the Intel ME FW updater
http://s000.tinyupload.com/index.php?file_id=35198791302204820694

You may run it in Windows (x64) by typing
FWUpdLcl64.exe -f 8.1.70.1590_1.5MB_PRD_RGN.bin
```

**Comment by mytbk** [comment]
NVME的支持简单，就是加一个模块。

**Comment by tofuliang** [comment]
在[这里](https://www.itmanbu.com/ami-bios-modification.html)看到同样是 X79 平台的MSR 0xE2 解锁方法，但是主板不一样，请问如何知道那个patch是否适用于我的主板呢？

**Comment by tofuliang** [comment]
搜了下UEFIPatch相关资料，确定是通用的，patch完了直接刷入，完事，真解锁了😁
